### ISSUE TITLE
Add "main" key to package.json to avoid defining direct path to the scss file when importing

### ISSUE THREAD

**Issue by certainlyakey** [danielguillan/quantity-queries#11]
Please add this to `package.json`:

```
"main": "stylesheets/_quantity-queries.scss",
```

This will allow us to import the package to Sass codebase like this `@import '~quantity-queries';` instead of like this `@import '~quantity-queries/stylesheets/quantity-queries';`.

Thanks!

**Comment by danielguillan** [comment]
`v0.5.0` of quantity-queries has been released. Thanks for the suggestion @certainlyakey and @AndersDJohnson for the PR!
