### ISSUE TITLE
Tag v0.4.0

### ISSUE THREAD

**Issue by jedfoster** [danielguillan/quantity-queries#7]
Please tag a release for v0.4.0. Currently, `bower install --save danielguillan/quantity-queries` installs v0.3.0.

Also, you might want to update your docs as `bower install --save quantity-queries` doesn't work at all; looks like there's another package named `quantity-queries`.

**Comment by danielguillan** [comment]
Thanks for the report @jedfoster!

Everything should work as expected now, including `bower install --save quantity-queries`.

**Comment by Heydon** [comment]
Just lurking and watching you dudes doing cool shit :+1:
