### ISSUE TITLE
Make compatible with sass eyeglass/publish to npm

### ISSUE THREAD

**Issue by strarsis** [danielguillan/quantity-queries#8]
It would be very helpful when this is also made compatible with sass eyeglass and published to npm.

**Comment by danielguillan** [comment]
Will do! Thanks for the suggestion.

**Comment by strarsis** [comment]
@danielguillan: PR ready: https://github.com/danielguillan/quantity-queries/pull/10

**Comment by danielguillan** [comment]
Thank you very much @strarsis! quantity-queries is now on npm!
